project:
    type: book
    output-dir: docs

book:
    title: Research Scientist Guide
    subtitle: Comprehensive Research Scientist Interview Notes and Guides
    author: Kundan Kumar
    # date: today
    date-format: iso
    favicon: favicon.png
    cover-image: TSAcov.png
    repo-url: https://github.com/kundan-kumarr/StatSphere/
    repo-branch: master
    repo-actions: [edit, issue]
    downloads: [pdf, epub]
    sharing: [twitter, facebook]
    page-navigation: true
    reader-mode: true
    sidebar:
        search: true
    chapters:
        - index.qmd
        - l01_stat_math.qmd
        - l02_ds.qmd
        - l03_algorithm.qmd
        - l04_data_pipe.qmd
        - l05_ml.qmd
        - l06_dl.qmd
        - l07_time_series.qmd
        - l08_drl.qmd
        - l09_model_eval.qmd
        - l10_llms.qmd
        - l11_llms_finetuning.qmd
        - l12_compression.qmd
        - l13_computervision.qmd
        - l14_multimodal.qmd
        - l15_casuality.qmd
        - l16_secureai.qmd
        - l17_scalability.qmd
        - l18_stattesting.qmd
        #- software.qmd
        - references.qmd
    appendices:
        - s1_wls.qmd
        - s2_gls.qmd
        - s4_trendsync.qmd
        - s6_extremes.qmd
        - s_practice.qmd

bibliography:
    - references.bib
    - refpackages.bib
csl: springerbasicVL.csl

appendix-style: default

format:
    html:
        code-fold: true
        code-link: true
        theme: cosmo
        fig-width: 8
        fig-height: 5

engine: knitr
knitr:
    opts_chunk:
        collapse: false
        message: false
        warning: false
        comment: "#>"
        R.options:
            knitr.graphics.auto_pdf: true
execute:
    eval: true
    echo: true
